### ISSUE TITLE
Correct measure_strehl NameError

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/poppy#138]
<a href="https://github.com/josePhoenix"><img src="https://avatars3.githubusercontent.com/u/172886?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [josePhoenix](https://github.com/josePhoenix)**
_Wednesday Jan 13, 2016 at 16:25 GMT_
_Originally opened as https://github.com/mperrin/poppy/issues/138_

----

A report via Kathryn St. Laurent: the code for `utils.measure_strehl` has rotted a bit. Shouldn't be a difficult fix.

```
[ssbdev-osx] [stlaurent:Work/NIRISS NRM/Code] kstlaurent% python Make_Models.py
Traceback (most recent call last):
  File "Make_Models.py", line 214, in <module>
    main()
  File "Make_Models.py", line 200, in main
    webbpsf_maker(pup,OPD)
  File "Make_Models.py", line 124, in webbpsf_maker
    strehl = poppy.utils.measure_strehl(HDUlist_or_filename=LOC+PSF_FILE%(pup,OPD,fltr), ext=0, slice=0, center=None, display=True, verbose=True, cache_perfect=False)
  File "/usr/stsci/ssbdev/python/lib/python2.7/site-packages/poppy/utils.py", line 866, in measure_strehl
    inst = Instrument(header['INSTRUME'])
NameError: global name 'Instrument' is not defined
```

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Thursday Jan 14, 2016 at 18:01 GMT_

----

Hmm, this is actually not going to be as simple as we might like. The `measure_strehl` function was originally written in the context of `webbpsf` prior to the `webbpsf`/`poppy` split into separate packages. It's actually trying to call the `webbpsf.Instrument` function, which returns a suitable instrument subclass instance if given a string name like "NIRSpec". That's very different from what's now become the `Instrument` parent class in `poppy.`

In the more generic case of `poppy` now, I don't see any feasible way for the `measure_strehl` function to automatically infer the correct Instrument class instance for computing the perfect PSF for deriving a Strehl ratio. 

Perhaps the best fix here is to move `measure_strehl` to `webbpsf`? And explicitly not try to tackle the much harder problem of providing a general Strehl calculator for arbitrary instruments in `poppy`.

**Comment by mperrin** [comment]
<a href="https://github.com/josePhoenix"><img src="https://avatars3.githubusercontent.com/u/172886?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [josePhoenix](https://github.com/josePhoenix)**
_Thursday Jan 14, 2016 at 20:56 GMT_

----

Ah yes.. I sometimes forget which repository things live in! Definitely was thinking in terms of a WebbPSF-specific solution.

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Monday Feb 08, 2016 at 22:08 GMT_

----

Code removed from poppy; present in webbpsf.
