### ISSUE TITLE
poppy.Instrument references CircularAperture incorrectly

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/poppy#24]
<a href="https://github.com/josePhoenix"><img src="https://avatars3.githubusercontent.com/u/172886?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [josePhoenix](https://github.com/josePhoenix)**
_Monday Dec 15, 2014 at 20:11 GMT_
_Originally opened as https://github.com/mperrin/poppy/issues/24_

----

Looks like CircularAperture got moved and nobody told Instrument. (I guess the WebbPSF `JWInstrument` class doesn't call the superclass `__init__` or we would see this when starting up WebbPSF?)

``` python
>>> poppy.Instrument()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "poppy/instrument.py", line 54, in __init__
    self.pupil = poppy_core.CircularAperture( *args, **kwargs)
AttributeError: 'module' object has no attribute 'CircularAperture'
```

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Monday Dec 15, 2014 at 23:35 GMT_

----

re: calling superclasses, there's probably not any good reason that it doesn't call the superclass **init**, apart from the tangled back history of this. 

Short version: JWinstrument class got developed first, with all its subclasses, then I later refactored things to try to make a more generic superclass in poppy that could be used for other instruments. But It's definitely not as cleanly organized as could be since the 'parent' class logically is actually a descendent, historically.  Agreed that further refactoring here is worth pursuing, as you mentioned in #26
