### ISSUE TITLE
poppy fails to install using pip3 in Python3 virtualenv

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/poppy#80]
<a href="https://github.com/kmdouglass"><img src="https://avatars1.githubusercontent.com/u/3697676?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kmdouglass](https://github.com/kmdouglass)**
_Tuesday Mar 10, 2015 at 16:18 GMT_
_Originally opened as https://github.com/mperrin/poppy/issues/80_

----

Hi all,
I've just setup a clean virtualenv named myEnv in which I attempted to install poppy from pip3. Here are the current versions of packages I setup in the virtualenv using the Python 3.4.1 interpreter. I'm using Debian Wheezy.

``` sh
(myEnv)douglass:~$ pip freeze
astropy==1.0.1
certifi==14.5.14
d2to1==0.2.11
docutils==0.12
ipython==3.0.0
Jinja2==2.7.3
jsonschema==2.4.0
MarkupSafe==0.23
matplotlib==1.4.3
mistune==0.5.1
nose==1.3.4
numpy==1.9.2
numpydoc==0.5
psutil==2.2.1
ptyprocess==0.4
pyfits==3.3
Pygments==2.0.2
pyparsing==2.0.3
pysynphot==0.9.6
python-dateutil==2.4.1
pytz==2014.10
pyzmq==14.5.0
requests==2.5.3
scipy==0.15.1
six==1.9.0
Sphinx==1.2.3
stsci.distutils==0.3.7
terminado==0.5
tornado==4.1
```

And the output from the install attempt:

``` sh
(myEnv)douglass:~$ pip3 install poppy
Collecting poppy
  Using cached poppy-0.3.4.tar.gz
    /home/douglass/.virtualenvs/myEnv/lib/python3.4/site-packages/pkg_resources/__init__.py:190: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behav
ior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you h
ave another use case requiring the tuple, please file a bug with the setuptools project describing that need.                                                                                                   
      stacklevel=1,
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-8io8bu2m/poppy/setup.py", line 71, in <module>
        cmdclassd = register_commands(PACKAGENAME, VERSION, RELEASE)
      File "/tmp/pip-build-8io8bu2m/poppy/.eggs/astropy_helpers-0.4.8-py3.4.egg/astropy_helpers/setup_helpers.py", line 409, in register_commands
        'build_ext': generate_build_ext_command(package, release),
      File "/tmp/pip-build-8io8bu2m/poppy/.eggs/astropy_helpers-0.4.8-py3.4.egg/astropy_helpers/setup_helpers.py", line 470, in generate_build_ext_command
        uses_cython = should_build_with_cython(packagename, release)
      File "/tmp/pip-build-8io8bu2m/poppy/.eggs/astropy_helpers-0.4.8-py3.4.egg/astropy_helpers/setup_helpers.py", line 1205, in should_build_with_cython
        fromlist=['release', 'cython_version'])
      File "/tmp/pip-build-8io8bu2m/poppy/poppy/__init__.py", line 78, in <module>
        from . import poppy_core
    Complete output from command python setup.py egg_info:
    /home/douglass/.virtualenvs/myEnv/lib/python3.4/site-packages/pkg_resources/__init__.py:190: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behav
ior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you h
ave another use case requiring the tuple, please file a bug with the setuptools project describing that need.                                                                                                   

      stacklevel=1,

    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-8io8bu2m/poppy/setup.py", line 71, in <module>

        cmdclassd = register_commands(PACKAGENAME, VERSION, RELEASE)

      File "/tmp/pip-build-8io8bu2m/poppy/.eggs/astropy_helpers-0.4.8-py3.4.egg/astropy_helpers/setup_helpers.py", line 409, in register_commands

        'build_ext': generate_build_ext_command(package, release),

      File "/tmp/pip-build-8io8bu2m/poppy/.eggs/astropy_helpers-0.4.8-py3.4.egg/astropy_helpers/setup_helpers.py", line 470, in generate_build_ext_command

        uses_cython = should_build_with_cython(packagename, release)

      File "/tmp/pip-build-8io8bu2m/poppy/.eggs/astropy_helpers-0.4.8-py3.4.egg/astropy_helpers/setup_helpers.py", line 1205, in should_build_with_cython

        fromlist=['release', 'cython_version'])

      File "/tmp/pip-build-8io8bu2m/poppy/poppy/__init__.py", line 78, in <module>

        from . import poppy_core

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8io8bu2m/poppy
```

Any idea how I can install poppy using Python3, or am I stuck with Python2? I also ran into a similar error when trying to install PyFFTW, but this is probably a secondary issue.

Thanks!

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Tuesday Mar 10, 2015 at 17:06 GMT_

----

Hi Kyle,
So far Poppy has only been tested and developed on Python 2, but adding support for 3 is in the plan for this semester.  Cc @cslocum @jlong @embray

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Tuesday Mar 10, 2015 at 17:07 GMT_

----

Whoops I meant cc @josephoenix, apologies

**Comment by mperrin** [comment]
<a href="https://github.com/kmdouglass"><img src="https://avatars1.githubusercontent.com/u/3697676?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kmdouglass](https://github.com/kmdouglass)**
_Tuesday Mar 10, 2015 at 20:59 GMT_

----

Ah OK thanks for the response! I'll give it a try with Python 2 then.

**Comment by mperrin** [comment]
<a href="https://github.com/josePhoenix"><img src="https://avatars3.githubusercontent.com/u/172886?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [josePhoenix](https://github.com/josePhoenix)**
_Tuesday Mar 10, 2015 at 21:58 GMT_

----

FYI, you may want to install from source. We have recently been dealing with some packaging issues, and only the current GitHub master is known to successfully install all its dependencies. (You may still have to install numpy separately, first, but that's an issue on their end.)

Instructions for installing a development version are here: http://pythonhosted.org/poppy/installation.html

**Comment by mperrin** [comment]
<a href="https://github.com/kmdouglass"><img src="https://avatars1.githubusercontent.com/u/3697676?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kmdouglass](https://github.com/kmdouglass)**
_Wednesday Mar 11, 2015 at 08:02 GMT_

----

Hi @josePhoenix,
Thanks for the suggestion. As you suggested, I tried installing from source after cloning the git repository. I used the same virtualenv with Python 3.4.1 as before, but received the following error using either _pip3_ or just _pip_. I'll probably stick with poppy in Python2 for now.

``` sh
(myEnv)douglass:~/Wobble/poppy$ pip3 install -e .
Obtaining file:///mnt/LEBZ/Users/Kyle-Michael-Douglass/Projects/Wobble/poppy
    Initializing astropy_helpers submodule with: `git submodule update --init -- astropy_helpers`
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/mnt/LEBZ/Users/Kyle-Michael-Douglass/Projects/Wobble/poppy/setup.py", line 71, in <module
>                                                                                                    
        cmdclassd = register_commands(PACKAGENAME, VERSION, RELEASE)
      File "/mnt/LEBZ/Users/Kyle-Michael-Douglass/Projects/Wobble/poppy/astropy_helpers/astropy_helper
s/setup_helpers.py", line 266, in register_commands                                                  
        'build_ext': generate_build_ext_command(package, release),
      File "/mnt/LEBZ/Users/Kyle-Michael-Douglass/Projects/Wobble/poppy/astropy_helpers/astropy_helper
s/commands/build_ext.py", line 63, in generate_build_ext_command                                     
        uses_cython = should_build_with_cython(packagename, release)
      File "/mnt/LEBZ/Users/Kyle-Michael-Douglass/Projects/Wobble/poppy/astropy_helpers/astropy_helper
s/commands/build_ext.py", line 23, in should_build_with_cython                                       
        fromlist=['release', 'cython_version'])
      File "/mnt/LEBZ/Users/Kyle-Michael-Douglass/Projects/Wobble/poppy/poppy/__init__.py", line 78, i
n <module>                                                                                           
        from . import poppy_core
    Complete output from command python setup.py egg_info:
    Initializing astropy_helpers submodule with: `git submodule update --init -- astropy_helpers`

    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/mnt/LEBZ/Users/Kyle-Michael-Douglass/Projects/Wobble/poppy/setup.py", line 71, in <module
>                                                                                                    

        cmdclassd = register_commands(PACKAGENAME, VERSION, RELEASE)

      File "/mnt/LEBZ/Users/Kyle-Michael-Douglass/Projects/Wobble/poppy/astropy_helpers/astropy_helper
s/setup_helpers.py", line 266, in register_commands                                                  

        'build_ext': generate_build_ext_command(package, release),

      File "/mnt/LEBZ/Users/Kyle-Michael-Douglass/Projects/Wobble/poppy/astropy_helpers/astropy_helper
s/commands/build_ext.py", line 63, in generate_build_ext_command                                     

        uses_cython = should_build_with_cython(packagename, release)

      File "/mnt/LEBZ/Users/Kyle-Michael-Douglass/Projects/Wobble/poppy/astropy_helpers/astropy_helper
s/commands/build_ext.py", line 23, in should_build_with_cython                                       

        fromlist=['release', 'cython_version'])

      File "/mnt/LEBZ/Users/Kyle-Michael-Douglass/Projects/Wobble/poppy/poppy/__init__.py", line 78, i
n <module>                                                                                           

        from . import poppy_core

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /mnt/LEBZ/Users/Kyle-Michael-Dougla
ss/Projects/Wobble/poppy                                                                             
```

**Comment by mperrin** [comment]
<a href="https://github.com/josePhoenix"><img src="https://avatars3.githubusercontent.com/u/172886?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [josePhoenix](https://github.com/josePhoenix)**
_Wednesday Mar 11, 2015 at 13:25 GMT_

----

Apologies, I meant that there was a packaging bug in our _Python 2.7_ support. If `pip install poppy` is working for you with Python 2.7, then disregard my comment :)

Python 3 support is on the agenda as part of the next release. Stay tuned!

**Comment by mperrin** [comment]
<a href="https://github.com/embray"><img src="https://avatars1.githubusercontent.com/u/676149?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [embray](https://github.com/embray)**
_Wednesday Mar 11, 2015 at 15:48 GMT_

----

At some point the build is trying to import from the poppy package and failing--likely due to something that is not valid syntax in Python 3.  Though it would be nice if that error were propagated higher up I guess.  It's weird that it's showing a traceback but not the exception that caused it.  I don't know if that's normal or not.

**Comment by mperrin** [comment]
<a href="https://github.com/josePhoenix"><img src="https://avatars3.githubusercontent.com/u/172886?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [josePhoenix](https://github.com/josePhoenix)**
_Wednesday Mar 11, 2015 at 15:56 GMT_

----

Entirely possible that it's this: https://github.com/mperrin/poppy/issues/70

I haven't had time to investigate the actual syntax error here. It wasn't obvious to me from looking at the lines.

**Comment by mperrin** [comment]
<a href="https://github.com/kmdouglass"><img src="https://avatars1.githubusercontent.com/u/3697676?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kmdouglass](https://github.com/kmdouglass)**
_Wednesday Mar 11, 2015 at 17:11 GMT_

----

@josePhoenix @embray 
It looks like the problem was exactly #70 

After applying the following patch, I managed to get poppy to install in a Python 3 environment. I could import the library as well in the environment, but poppy.test() raised a whole bunch of errors. I'll let you guys work on those when you migrate the code to Python3 compatibility :)

``` sh
--- poppy_core_backup.py    2015-03-11 17:48:03.789102500 +0100
+++ poppy_core.py   2015-03-11 17:55:39.050157100 +0100
@@ -2094,10 +2094,10 @@

             if len (self.opd.shape) != 2 or self.opd.shape[0] != self.opd.shape[1]:
                 _log.debug('OPD shape: '+str(self.opd.shape))
-                raise ValueError, "OPD image must be 2-D and square"
+                raise ValueError("OPD image must be 2-D and square")

             if len (self.amplitude.shape) != 2 or self.amplitude.shape[0] != self.amplitude.shape[1]:
-                raise ValueError, "Pupil amplitude image must be 2-D and square"
+                raise ValueError("Pupil amplitude image must be 2-D and square")


             assert self.amplitude.shape == self.opd.shape
```

**Comment by mperrin** [comment]
<a href="https://github.com/josePhoenix"><img src="https://avatars3.githubusercontent.com/u/172886?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [josePhoenix](https://github.com/josePhoenix)**
_Wednesday Mar 11, 2015 at 17:17 GMT_

----

Aha! Yep, that definitely wasn't future-proof syntax. Let us know if you have issues. The test suite has ~80% coverage, if I recall correctly, so it should be a good way to check.

**Comment by mperrin** [comment]
<a href="https://github.com/kmdouglass"><img src="https://avatars1.githubusercontent.com/u/3697676?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kmdouglass](https://github.com/kmdouglass)**
_Wednesday Mar 11, 2015 at 17:36 GMT_

----

If it helps, I placed the output from `poppy.test()` and `pip freeze` at this location:

https://drive.switch.ch/public.php?service=files&t=ddeb9ccca3f08b1fd197f662427b6af5

This is essentially what happens after fixing the syntax error in poppy_core.py and installing poppy using pip in Python 3.

I'll leave it at that for now, since I have it working in Python 2. Thanks again.

**Comment by mperrin** [comment]
<a href="https://github.com/josePhoenix"><img src="https://avatars3.githubusercontent.com/u/172886?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [josePhoenix](https://github.com/josePhoenix)**
_Wednesday Mar 11, 2015 at 18:15 GMT_

----

Thanks very much! It looks like we don't have 2to3 running in the build, or else we wouldn't have so many syntax errors. That'll go on our list of things to look at.

**Comment by mperrin** [comment]
<a href="https://github.com/josePhoenix"><img src="https://avatars3.githubusercontent.com/u/172886?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [josePhoenix](https://github.com/josePhoenix)**
_Friday Apr 10, 2015 at 15:59 GMT_

----

@kmdouglass See #86 for progress on this issue. If you'd like to try it out with Python 3, make a new virtualenv and install with `pip` as follows:

`pip install -e git+https://github.com/josePhoenix/poppy.git@py3#egg=poppy`

To run the test suite, you must additionally `pip install pytest`. Then change directories to where pip cloned the POPPY source, and run `python setup.py test`.

**Comment by mperrin** [comment]
<a href="https://github.com/josePhoenix"><img src="https://avatars3.githubusercontent.com/u/172886?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [josePhoenix](https://github.com/josePhoenix)**
_Monday Apr 13, 2015 at 04:13 GMT_

----

This is now merged in to master, and our next release will be compatible with Python 3.4 as well as 2.7.
